"""empty message

Revision ID: 0a177456b109
Revises: dd85c505f51f
Create Date: 2018-03-07 20:42:56.393820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a177456b109'
down_revision = 'dd85c505f51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('org', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'org')
    # ### end Alembic commands ###
