"""empty message

Revision ID: 788b00d34c72
Revises: 0433a67cb10b
Create Date: 2018-03-06 06:33:27.449445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788b00d34c72'
down_revision = '0433a67cb10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('org', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'org')
    # ### end Alembic commands ###
