"""empty message

Revision ID: 93e48903a45d
Revises: c35fe1323c8c
Create Date: 2018-02-22 18:09:38.838142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93e48903a45d'
down_revision = 'c35fe1323c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'last_journal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('last_journal', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
