"""empty message

Revision ID: dd85c505f51f
Revises: 788b00d34c72
Create Date: 2018-03-06 06:51:12.281861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd85c505f51f'
down_revision = '788b00d34c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('authors', sa.String(length=170), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'authors')
    # ### end Alembic commands ###
