"""empty message

Revision ID: dfe9bdfb19ca
Revises: 0a177456b109
Create Date: 2018-03-07 21:16:53.501005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfe9bdfb19ca'
down_revision = '0a177456b109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_ibfk_1', 'author', type_='foreignkey')
    op.drop_column('author', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('organization_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('author_ibfk_1', 'author', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
