"""empty message

Revision ID: ef62f86906bb
Revises: f963571e21c8
Create Date: 2018-04-23 21:45:12.244909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef62f86906bb'
down_revision = 'f963571e21c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='coauthor')
    op.drop_index('slug', table_name='coauthor')
    op.create_foreign_key(None, 'coauthor', 'author', ['id'], ['id'])
    op.drop_column('coauthor', 'f2_name')
    op.drop_column('coauthor', 'dolzh')
    op.drop_column('coauthor', 'slug')
    op.drop_column('coauthor', 'stepen')
    op.drop_column('coauthor', 'phone')
    op.drop_column('coauthor', 'email')
    op.drop_column('coauthor', 'zvanie')
    op.drop_column('coauthor', 'organization')
    op.drop_column('coauthor', 'f_name')
    op.drop_column('coauthor', 'l_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coauthor', sa.Column('l_name', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('coauthor', sa.Column('f_name', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('coauthor', sa.Column('organization', mysql.TEXT(), nullable=True))
    op.add_column('coauthor', sa.Column('zvanie', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('coauthor', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('coauthor', sa.Column('phone', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('coauthor', sa.Column('stepen', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('coauthor', sa.Column('slug', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('coauthor', sa.Column('dolzh', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('coauthor', sa.Column('f2_name', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'coauthor', type_='foreignkey')
    op.create_index('slug', 'coauthor', ['slug'], unique=True)
    op.create_index('email', 'coauthor', ['email'], unique=True)
    # ### end Alembic commands ###
