"""empty message

Revision ID: f963571e21c8
Revises: 0b5893014638
Create Date: 2018-03-30 20:41:16.792430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f963571e21c8'
down_revision = '0b5893014638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('f2_name', sa.String(length=80), nullable=True))
    op.add_column('coauthor', sa.Column('f2_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coauthor', 'f2_name')
    op.drop_column('author', 'f2_name')
    # ### end Alembic commands ###
